wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714208967.434339
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 103
      3:
      - 2
      - 13
      - 23
      4: 3.11.3
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
